Xiyue enddate create form
ucsb-cs156-w22/team04-w22-7pm-HappyCows pull request #65
Opened 2022-03-12 01:58 UTC by xiyuewang556633

# Overview

Allow Users to set end date when creating a commons. Then it will be displayed on play page.

# Details

https://user-images.githubusercontent.com/59850013/157999365-6acefe0c-5200-477d-8ca4-c3cf94409414.mov

## Reminders (delete this section before merging or as code is merged)
- [ ] Explicitly link to this pull request each issue that it closes
- [ ] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

2022-03-12 02:34 UTC, vChase42 approved these changes, later dismissed
Shows up for me on Heroku and localhost, LGTM

2022-03-12 07:11 UTC, vChase42 approved these changes, later dismissed
LGTM

2022-03-13 04:55 UTC, vChase42 approved these changes, later dismissed
LGTM

2022-03-13 05:01 UTC, isaacchin approved these changes, later dismissed
LGTM

2022-03-13 22:29 UTC, pconrad requested changes
LGTM except for restoring the iso-dates

2022-03-13 22:29 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "startDate": "6/10/2021",
Per Xiyue, these should be ISO dates; that's what's returned by the backend.

So let's make the fixtures match

2022-03-14 00:45 UTC, pconrad approved these changes
LGTM

2022-03-14 00:45 UTC, merged